In [ ]:
l1 = [1,2,4,6]
l2 = [2,6,4,9]
l1 + l2

    

[1, 2, 4, 6, 2, 6, 4, 9]

In [1]:
import numpy as np
l1 = [1,2,4,6]
l2 = [2,6,4,9]
arr1 = np.array(l1)
arr2 = np.array(l2)
print(type(arr1))

<class 'numpy.ndarray'>


In [5]:
print(arr1 + 10)

[11 12 14 16]


In [6]:
arr1.ndim  #to check the dimension

1

In [ ]:
arr1.shape # to check the number of colomns and rows

(4,)

In [8]:
arr1.dtype

dtype('int64')

In [10]:
arr3 = np.array([1,2,3,4,'a'])
arr3.dtype

dtype('<U21')

In [11]:
arr4 = np.array([[1,2,8],[4,6,7],[2,8,9]])
arr4

array([[1, 2, 8],
       [4, 6, 7],
       [2, 8, 9]])

In [14]:
arr4.size
arr4.shape
arr4.dtype
arr4.ndim

2

In [ ]:
print(list(range(5,10))) # normal

[5, 6, 7, 8, 9]


In [16]:
print(np.arange(10,100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [18]:
arr5 = np.arange(10,100,10)
print(arr5)

[10 20 30 40 50 60 70 80 90]


In [21]:
arr6 = np.arange(3,21)
print(arr6.reshape(3,6))
print(arr6)

[[ 3  4  5  6  7  8]
 [ 9 10 11 12 13 14]
 [15 16 17 18 19 20]]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
import time
a = range(1000000)
b = range(1000000)
start = time.time()
c = []
for x,y in zip(a,b):
    su = x + y
    c.append(su)
end = time.time()
print("total time taken :",(end-start)*1000)    

total time taken : 506.1984062194824


In [ ]:
# array slicing
import numpy as np
arr = np.arange(16)
print(arr)
print(arr[5:11])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 5  6  7  8  9 10]


In [7]:
arr2 = np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13]])
print(arr2)
print(arr2[2])

[[ 1  2  3  4]
 [ 6  7  8  9]
 [10 11 12 13]]
[10 11 12 13]


In [10]:
print(arr2[2,1])
print(arr2[[1,2]])

11
[[ 6  7  8  9]
 [10 11 12 13]]


In [14]:
print(arr2[1:,1:3])
print("\n")


print(arr2[:,[0,2]])

[[ 7  8]
 [11 12]]


[[ 1  3]
 [ 6  8]
 [10 12]]


In [16]:
print(arr2.mean())

7.166666666666667


In [18]:
print(arr2.mean(axis = 1)) # row wise
print(arr2.mean(axis = 0)) # colomn wise

[ 2.5  7.5 11.5]
[5.66666667 6.66666667 7.66666667 8.66666667]


In [24]:
# abs,sqrt
import numpy as np
arr3 = [2,4,-9,4]
arr3 = np.abs(arr3)
arr3
print(np.sqrt(arr3))

[1.41421356 2.         3.         2.        ]


In [27]:
# to find the varience
# varience  = sigma 
arr5 = np.arange(5)
print(np.var(arr5))
ans = np.sum(np.pow(arr5 - np.mean(arr5),2))/np.size(arr5)
print(ans)

2.0
2.0


In [28]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [34]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
x = np.arange(25).reshape(5,5)
x
print(x.diagonal())

[ 0  6 12 18 24]


In [38]:
A = np.arange(8)
B = np.arange(8)
print(A.dot(B))

140


In [ ]:
a = np.zeros((4,4))
b = np.ones((4,4))
# vertical stacking the no of colomns should be same
np.vstack((a,b))
np.hstack((a,b))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.concatenate([a,b])  # vertical stack

np.concatenate([a,b],axis = 1)  # horizontal stacking

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [45]:
a
a.flatten()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
np.random.rand(2,2)

array([[0.69703538, 0.74791458],
       [0.44168245, 0.05098819]])

In [47]:
np.random.randn(3) #normal distribution

array([ 0.59907142, -0.64023796, -0.7902608 ])

In [48]:
np.random.randint(4,100,4)

array([ 6, 31, 40, 91], dtype=int32)

In [51]:
rollno = np.arange(1,21)
np.random.shuffle(rollno)
rollno

array([20, 13, 16,  4,  9, 15, 19, 14, 11, 10, 17,  5,  3, 18,  2,  7,  1,
       12,  6,  8])