In [9]:
import numpy as np
a = np.array([1,2,3],dtype = "int16")
print(a)

[1 2 3]


In [2]:
b = np.array([[8.0,9.0,1.0],[1,4,7]])
print(b)

[[8. 9. 1.]
 [1. 4. 7.]]


In [4]:
# to get the dimension
a.ndim
b.ndim

2

In [ ]:
a.shape  # if the array is 1D which gives the number of columns

(3,)

In [6]:
b.shape

(2, 3)

In [10]:
a.dtype

dtype('int16')

In [14]:
a.itemsize
a.nbytes

6

In [15]:
b.nbytes

48

In [12]:
a.size

3

In [13]:
b.size

6

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
print(a[1,5])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13


In [18]:
    # get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [20]:
#get a column
print(a[:,2])

[ 3 10]


In [21]:
print(a[0,1:6:1])

[2 3 4 5 6]


In [22]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [23]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
print(b[0,1,1])

4


In [25]:
# replace
print(b[:,1,:])

[[3 4]
 [7 8]]


In [27]:
b[:,1,:] = [[1,9],[8,3]]
print(b)

[[[1 2]
  [1 9]]

 [[5 6]
  [8 3]]]


In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [30]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [31]:
np.ones((4,5),dtype = "int32")

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [32]:
# to fill with other numbers
np.full((2,3),99)

array([[99, 99, 99],
       [99, 99, 99]])

In [33]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [34]:
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [35]:
np.random.rand(4,2)

array([[5.00341400e-01, 4.12327602e-04],
       [3.81859312e-01, 2.89525924e-01],
       [3.20286299e-02, 5.53285231e-01],
       [5.13188398e-01, 3.54520540e-01]])

In [37]:
np.random.randint(10,40,size = (3,3))

array([[28, 17, 32],
       [35, 27, 28],
       [21, 32, 35]], dtype=int32)

In [38]:
np.identity( 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [41]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [48]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z

z[1,1] = 9
z
output[1:4,1:4] = z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# be caefull coping arrays

a = np.array([1,2,3])
b = a
b
b[0] = 100
print(b,"\n",a)  # even  the array a itself changed 


# to avoid thatr make the copy of a

[100   2   3] 
 [100   2   3]


In [56]:
# to avoid thatr make the copy of a
a = np.array([1,2,3])
b = a.copy()
b[1] = 100
a

array([1, 2, 3])

In [ ]:
# mathematics

a = np.array([1,2,3,4])
a+10
a-10



array([-9, -8, -7, -6])

In [60]:
a-10

array([-9, -8, -7, -6])

In [61]:
a/10

array([0.1, 0.2, 0.3, 0.4])

In [62]:
a**2

array([ 1,  4,  9, 16])

In [63]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [68]:
# linear algeabra

# matrix multiplication

a = np.ones((2,3))
a
b = np.full((3,2),2)
b

np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [ ]:
# determinant

c = np.identity(4)
np.linalg.det(c)



np.float64(1.0)

In [72]:
# statistics

stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:

np.mean(stats)
np.min(stats)

np.int64(1)

In [76]:
np.min(stats,axis = 1)

array([1, 4])

In [77]:
np.sum(stats,axis = 0)

array([5, 7, 9])

In [81]:
# reorganising arrar

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before.shape)

(2, 4)


In [ ]:
after  = before.reshape(4,2)  # can be maek to (2,2,2)
after


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
# vertically  stacking

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v2])   


array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [87]:
# horizontal

np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 7, 8, 5, 6, 7, 8])

In [92]:
filedata = np.genfromtxt("data.txt",delimiter=",")
filedata = filedata.astype("int32")    

In [90]:
# boolean indexing and advanced indexing

filedata >50

array([False, False, False, False, False])

In [93]:
filedata[filedata>2]

array([3, 4, 5], dtype=int32)

In [ ]:
# u can index a list in numpy
