In [1]:
from sklearn import preprocessing
import numpy as np


In [2]:
x = np.array([
    [1,1,10],
    [2,2,12],
    [3,4,15]
])
x

array([[ 1,  1, 10],
       [ 2,  2, 12],
       [ 3,  4, 15]])

In [3]:
# degree 2
poly = preprocessing.PolynomialFeatures(2)
poly.fit_transform(x)


array([[  1.,   1.,   1.,  10.,   1.,   1.,  10.,   1.,  10., 100.],
       [  1.,   2.,   2.,  12.,   4.,   4.,  24.,   4.,  24., 144.],
       [  1.,   3.,   4.,  15.,   9.,  12.,  45.,  16.,  60., 225.]])

In [5]:
poly = preprocessing.PolynomialFeatures(degree=2,interaction_only=True)  # which avoids the square
poly.fit_transform(x)

array([[ 1.,  1.,  1., 10.,  1., 10., 10.],
       [ 1.,  2.,  2., 12.,  4., 24., 24.],
       [ 1.,  3.,  4., 15., 12., 45., 60.]])