In [1]:
import torch

In [2]:
import numpy as np

In [5]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data
print(type(x_data))

<class 'torch.Tensor'>


In [12]:
np_array = np.array(x_data)
x_np = torch.from_numpy(np_array)
print(type(np_array))
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


C:\Users\salah\AppData\Local\Temp\ipykernel_15520\1320052608.py:1: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments. To learn more, see the migration guide https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
  np_array = np.array(x_data)


In [15]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.1196, 0.5640],
        [0.5169, 0.6112]])


In [18]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
zero_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"ones Tensor: \n {ones_tensor} \n")
print(f"zero Tensor: \n {zero_tensor}")


Random Tensor: 
 tensor([[0.5075, 0.4985, 0.0308],
        [0.3943, 0.6647, 0.2003]]) 

ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [19]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [ ]:
if torch.accelerator.is_available():
    print('available')
else:
    print('not')    

not
