In [2]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data
print(type(x_data))

<class 'torch.Tensor'>


In [4]:
np_array = np.array(x_data)
x_np = torch.from_numpy(np_array)
print(type(np_array))
print(type(x_np))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [5]:
x_ones = torch.ones_like(x_data)
print(x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.0174, 0.9207],
        [0.7168, 0.1768]])


In [6]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
zero_tensor = torch.zeros(shape)
ones_tensor = torch.ones(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"ones Tensor: \n {ones_tensor} \n")
print(f"zero Tensor: \n {zero_tensor}")

Random Tensor: 
 tensor([[0.2208, 0.3464, 0.3686],
        [0.4401, 0.2513, 0.3029]]) 

ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

zero Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [7]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [13]:
if torch.accelerator.is_available():
  tensor = tensor.to(torch.accelerator.current_accelerator())

In [14]:
if torch.accelerator.is_available():
    print('available')
else:
    print('not')

available


In [9]:
import os
import pandas as pd
from torch.utils.data import Dataset
from torchvision.io import decode_image

In [12]:
class CustomImageDataset(Dataset):
  def __init__(self,annotations_file,img_dir,tranform = None,target_transform = None):
    self.img_labels = pd.read_csv(annotations_file)
    self.img_dir = img_dir
    self.tranform = tranform
    self.target_transform = target_transform

  def __len__(self):
    return len(self.img_labels)

  def __getitem__(self,idx):
    img_path = os.path.join(self.img_dir,self.img_labels.iloc[idx,0])
    image = decode_image(img_path)
    label = self.img_labels.iloc[idx,1]
    if self.tranform:
      image = self.tranform(image)
    if self.target_transform:
      label = self.target_transform(label)
    return image,label

In [18]:
train_datasetloader = CustomImageDataset("/content/annotations - Sheet1.csv","/content/train")

In [19]:
train_datasetloader.__len__()

2